url: https://soundclim.github.io/chorus/
title:  Juan Sebastián Ulloa
description: Scientist and engineer developing smart tools for ecology and biodiversity conservation
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  is_project_page: true
  email: julloa@humboldt.org.co
  github_url: https://github.com/juansulloa
  linkedin_url: https://co.linkedin.com/in/jseb-ulloa
  orcid_url: https://orcid.org/0000-0001-5666-6942
  googlescholar_url: https://scholar.google.com/citations?user=xdHmzxcAAAAJ&hl=en&oi=ao
  owner_name: Juan Sebastián Ulloa
  owner_url: https://github.com/orgs/soundclim/people
  repository_name: jsulloa
  repository_url: https://github.com/soundclim/anuraset
