url: https://soundclim.github.io/chorus/
title:  Juan Sebastián Ulloa
description: Scientist and engineer developing smart tools for ecology and biodiversity conservation
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  is_project_page: true
  github_url: https://doi.org/10.5281/zenodo.8056090
  googlescholar_url: https://arxiv.org/abs/2307.06860
  owner_name: Juan Sebastián Ulloa
  owner_url: https://github.com/orgs/soundclim/people
  repository_name: jsulloa
  repository_url: https://github.com/soundclim/anuraset
